### ISSUE TITLE
Pin 8

### ISSUE THREAD

**Issue by cagdask** [architbubber/MultiWii-Nrf24l01-SingleBoard#1]
Hi Thanks for the great repo! I loved it. It is really close to my configuration but I am using pin 8 instead of 7 for the radio. I realized you are using still writing to pin 8 for some reason. What is that for? and can you give any suggestions to change the pin to 8?

**Comment by architbubber** [comment]
What is the problem in using pin 7 ? 
Pin 8 is used by Multiwii for buzzer . If you want to change that, you'll have to go through all files and check wherever they are utilising pin 8. Since you need pin 8 for CE(Clock Enable), you'll have to initialise it in the same manner as I have done for pin 7. 
That's a whole lot of work, better use pin 7.

**Comment by cagdask** [comment]
My hardware configuration is different. Fortunately, Pin 8 is not used that much. I have mainly commented pin8 usages in NRF24_RX.cpp. If it is used by buzzer, in Multiwii it might be good idea to conditionally use it in NRF24_RX.cpp by checking the preprocessor directive.

**Comment by architbubber** [comment]
I think your issue has been resolved then.
