### ISSUE TITLE
PWM output not read by the ESC's

### ISSUE THREAD

**Issue by anchitbhuhan** [architbubber/MultiWii-Nrf24l01-SingleBoard#3]
Hi,
I have a similar setup with Arduino connected with Magnetometer, Accelerometer and Barometer. I am able to receive all Data (Throttle, Yaw, Pitch, Roll) from a Custom RC which i built using Arduino.

I have my 4 ESC connection to A0, A1, A2, A3 Analog pins on Arduino Nano. So i modified the code in Output.cpp to the correct Pins
![image](https://user-images.githubusercontent.com/29230917/166741238-15d84196-d37e-4a3a-9cca-d7c6022cf056.png)

But , The motors do not spin, However, i am able to see thrust in the 4 Arms in the Multiwii GUI.

Any suggestions on why am i getting this ?

**Comment by architbubber** [comment]
You should thoroughly read and understand the code before making any changes. In output.cpp it is mentioned as:
`/**************************************************************************************/
/***************                  Motor Pin order                  ********************/
/**************************************************************************************/
// since we are uing the PWM generation in a direct way, the pin order is just to inizialie the right pins 
// its not possible to change a PWM output pin just by changing the order`
If the pins order can't be changed then how can the pin mapping change ?

**Comment by architbubber** [comment]
There are 3 points I would like to quote,

1. For changing pins you would have to go through the output.cpp and understand how it is taking the pins. (Because it's making use of AVR programming and direct register calls) and then change that in the whole code.

2. MultiWii focuses on use of hardware PWM while your approach would require soft PWM signal to be generated from the analog pins which will require a lot of work.

3. These are analog pins first of all and then these are already being utilised by the code for various purpose like Battery voltage .etc so using these pins would require you to go through all the files and make changes.

Hence I would say choose a different board if you are facing shortage of pins or a different approach .
Ask if you have any other query I'll be happy to help.

~Archit
